### ISSUE TITLE
[Vite] Function not deploying with Azure SWA

### ISSUE THREAD

**Issue by halljus** [scandinavianairlines/remix-azure-functions#71]
First, thanks for your work on this and for making it available to the public!

We're trying to deploy a Remix Vite app as an Azure Static Web App using your `createRequestHandler` function and can't quite seem to get it to work (via the Azure SWA CLI). After deploying, static assets are served up properly but it doesn't appear the Azure Function gets created so every other non-static-asset request fails (404). We don't get any related errors during deployment, as far as we can tell.

As a sanity check, we attempted to deploy your non-Vite example SWA project and that is behaving in the exact same way - static assets work, other routes (the Azure Function) do not.

Some questions for you:

1. Should there be some indication in the Azure portal web UI that a function was created and exists within the SWA? The only indication I have right now is when I go to Application Insights, it says `App Insights is only applicable to Static Web Apps with at least one function. Add a function to your app to enable App Insights.` - which makes me think the function did not get created.
2. What is the appropriate situation for `node_modules`? We've been trying all these deployments with `node_modules` in the root of the project and no `server/node_modules` - but it dawned on us that the deployment may not run `npm install` once the function code is deployed, meaning the necessary `node_modules` for the function would not be there at runtime. But if we include `server/node_modules`, the deployment fails because the API Zip is too big (errors with `Reason: The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.`).
3. Should this work on the Free hosting plan? Someone said you need to be on the Standard hosting plan for functions to work in an SWA. We tried both, no difference in behavior. Just curious if you know for sure.

Any guidance you could provide would be most appreciated. 🙏 

Thank you!

**Comment by lfantone** [comment]
Thanks for reaching out!

Just to mention, we are currently using this in our production environment for different remix application with _vite_ and _without vite_. There is also a working example in the SWA example readme, maybe you can find that useful!

Answering your questions:

1. Once a deploy is made, you should be able to "see" your function under the **APIs** section. You can access through the sidebar, under _Settings_.

<img width="915" alt="image" src="https://github.com/scandinavianairlines/remix-azure-functions/assets/850110/0cd27568-25cb-4edf-a9e5-b44502f278c6">

If the Function is not there, my suggestion would be to:
  a. Try to start the function locally, either with the Azure Functions emulator using the `azure-functions-core-tools`.
  b. Check the logs to see if there is any start-up issue with your function.
 
2. I think this depends on how you bundle your application and each case is unique. First, is possible to tell Azure to run `npm install --production`, you can check more [here](https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions).
Secondly, we used managed functions which means that we are deploying the function by itself by packing everything into a zip file with the _node_modules_. Again, I do think that this depends quite a lot on your stack and how you are managing your deployments.

3. Yes, doesn't really matter in which Plan you are. The working example is on the Free tier.

If you like, you can create an small reproduction case where we can take a look and see what's going on.

**Comment by halljus** [comment]
> There is also a working example in the SWA example readme, maybe you can find that useful!

We couldn't get that to work, either. It does the same thing as ours (no function created). ☹️ 

As for ours, everything runs great locally when we run `npm run simulate-azure` given the following package.json scripts:

```
"simulate-azure": "run-p simulate-azure:*",
"simulate-azure:swa": "swa start ./build/client --api-location ./server --port 3000 --api-devserver-url http://127.0.0.1:3030",
"simulate-azure:function": "func start --prefix server/ --cors-credentials --port 3030"
```

We can then browse `http://localhost:3000` and it renders the index route as expected.

We're deploying like so:

```
npx cross-env SWA_CLI_DEPLOYMENT_TOKEN=<AZURE_SWA_DEPLOYMENT_TOKEN> swa deploy --no-use-keychain --verbose=silly
```

All the log output from that command looks like it should have worked (no errors, gives us a smiley face and a URL at the end).

We're doing managed functions as well (got past the 100MB limit by only installing production deps in the `server` directory, like you mentioned above). But even though the deploy appears to succeed, the function does not get created.

---

Maybe this has something to do with our deployment approach? So far, this has just been an experiment to see if we could get it to work, so we've just been trying to deploy from the CLI on our local dev machines. Under normal circumstances, we would use GitHub Actions to deploy. But we wanted to get it to work manually first. Maybe the GitHub Action does something extra that we're not aware of and/or can't reproduce manually?

I can create a small reproduction repo but like I said, the example doesn't work for us either, so it might not be too valuable.

Thanks so much for your help on this!

**Comment by halljus** [comment]
Here's the project we're using (minimal repro): https://github.com/halljus/remix-swa

**Comment by lfantone** [comment]
Right, It could be related on how the output is being generated using `vite`. We can add a new example using vite instead

**Comment by halljus** [comment]
A working example would be great! 🙏

**Comment by lfantone** [comment]
Here is a working example with `vite`:

https://github.com/scandinavianairlines/remix-azure-functions/pull/76

There are a few things to take into consideration, I try to wrote all of the in the readme file. If you still can't deploy it, let us know!

**Comment by lfantone** [comment]
The deploy succeeding but no logs about what's going on is quite common on Azure 😅 
My though on what's going on is that the package deployed as a function is not right, so the function cannot start.

Make sure of:

1. The SWA CLI is picking the right _staticwebapps.config.json_ file. Looking at the logs, is using one from `/public` while it should be `build/client`.
2. Double check what SWA is deploying as a function. Not sure if there is another way, but what I usually do is to grab the zip file generated by SWA CLI on deploy and see what's inside.
3. Make sure that the `build/server` is part of the function package

**Comment by halljus** [comment]
I can't get your example to work, either - it behaves in an identical way (says it succeeds, but no function deployed).

1. Do you know why it would matter which `staticwebapp.config.json` it uses? The one in `build/client` is just copied from `public` by the Vite build process, so they are identical. The logs from deploying your example also reference the copy in `public`, for what it's worth.
2. I looked at the zip already and it contains what I would expect: the contents of the `server` directory, including `node_modules` and `build/server/index.js`. 🤷‍♂️ 
3. Yep, confirmed.

**Comment by halljus** [comment]
I just tried deploying your example on my personal device/network/Azure account and it does the exact same thing (no function gets deployed). So that eliminates my enterprise work environment, at least.

You've successfully deployed your Vite example? I must just be missing a step or something... 😅

**Comment by Sarabadu** [comment]
You can try looking into the logs.

The easiest way is to query

`traces`

Check if you see some logs saying 

X functions found 
X functions loaded 

If you get more "found" that loaded there is usually also some logs with the node style exception.

Hope it helps

**Comment by halljus** [comment]
> You can try looking into the logs.
> 
> The easiest way is to query
> 
> `traces`
> 
> Check if you see some logs saying
> 
> X functions found X functions loaded
> 
> If you get more "found" that loaded there is usually also some logs with the node style exception.
> 
> Hope it helps

Thanks for the suggestion. What logs? Where? I have the SWA CLI log output set at the most verbose level and there's nothing in there (see above). I see no logs available on the SWA in the Azure Portal (Application Insights is only available if there is a function present, which there isn't).

**Comment by lfantone** [comment]
There is no logs as application insights is not initialised yet 😂 , chicken and the egg story here...

The example is deployed and working, you have the URL in the readme.

- Silly question, but do you have a `host.json` file in the root of the function right?
- Are you still trying to deployed what you share in the reproduction repository?

Again, to me this points that you are missing a dependency on your function. If the vite build doesn't have declare the `noExternal` optional, you need to also include all the dependencies from the UI.

**Comment by halljus** [comment]
It works! 🎉 

So... the only difference was we were using `npm` (not allowed to use `yarn`). I guess now we need to determine what on earth is happening with npm. 😕 

For reference, we were doing this:

```sh
npm install
cd server
npm install --omit=dev
cd ..
```

**Comment by halljus** [comment]
OK, so I jumped to an invalid conclusion there. It had nothing to do with yarn-vs-npm, it was just the `import * as build from './build/server/index.js';` change. 😅

**Comment by halljus** [comment]
I think this concludes the experiment. Thanks so much for all your help @lfantone!

**Comment by lfantone** [comment]
I'm removing the vite dev server from the example to make it easier and clear for everyone.
