### ISSUE TITLE
 azure-staticwebapp-vite example README typo?

### ISSUE THREAD

**Issue by olivier-o** [scandinavianairlines/remix-azure-functions#84]
in the readme it is stated:  "The above configuration will forward all the requests to the /api/ssr function, which is defined in the server/handler.js file."
in   azure-staticwebapp-vite there is not `server/handler.js` file
also when running the example with `yarn dev` command, any request to `http://localhost:3000/` is returning a 404
```
[swa]
[swa] Found configuration file:
[swa]   /dev/remix-azure-functions/examples/azure-staticwebapp-vite/public/staticwebapp.config.json
[swa]
[swa]
[swa] Serving static content:
[swa]   /dev/remix-azure-functions/examples/azure-staticwebapp-vite/build/client
[swa]
[swa] Using dev server for API:
[swa]   http://127.0.0.1:3030
[swa]
[swa] Azure Static Web Apps emulator started at http://localhost:3000. Press CTRL+C to exit.
[swa]
[swa]
[2024-04-10T21:07:56.746Z] Host lock lease acquired by instance ID '00000000000000000000000001765947'.
[swa] GET http://127.0.0.1:3030/api/ssr (proxy)
[swa] GET http://localhost:3000/api/ssr - 404
```

**Comment by lfantone** [comment]
You are right! It's referring to `server/index.js` which is the function main handler.
Running SWA in your local won't work out of the box, requires some handling of the request to serve the right files.
That is something that we are currently working on

**Comment by olivier-o** [comment]
let me know if I can help you out on the SWA running locally.

**Comment by lfantone** [comment]
Docs has been updates, closing the issue as the dev environment with vite needs a separe discussion.
